### PR TITLE
First Implementation of the Python Simulator

### PR DESCRIPTION
**Pull request by Olshansk**
## Description

Tooling (in the form of python scripts and documentation) to generate RainTree unit tests.

## Origin Document

This was originally implemented to support unit test in the primary V1 implementation but we decided that it belongs in a separate simulator dedicate repository: https://github.com/pokt-network/pocket/pull/316

## Type of change

Please mark the relevant option(s):

- [x] New feature, functionality or library
- [ ] Bug fix
- [x] Code health or cleanup
- [ ] Major breaking change
- [ ] Documentation
- [x] Other: Test Tooling

## List of changes

- Python code that simulates RainTree using BFS (Breadth First Search)
- Python script that generates a Golang RainTree unit test using the results of the simulation
- Makefile target to help generate RainTree unit tests for a specific number of nodes
- Supporting README documentation

## Demo

![raintree_test](https://user-images.githubusercontent.com/1892194/197281791-798bebde-b9c3-445b-9e6f-c3d564ef2a46.gif)

## Testing

1. Generate a new test with the following command:

```bash
rainTreeTestOutputFilename=/tmp/answer.go numRainTreeNodes=12 make p2p_test_generator
```
2. Copied the output from `/tmp/answer.go` to `module_raintree_test.go`  the main V1 repo: https://github.com/pokt-network/pocket
3. Add comments to the tree visualization
4. Run `make test_p2p`

```go
//                                                                                                            val_1                                                                                                                                                                                                                
//                                     ┌────────────────────────────────────────────────────────────────────────┴───────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────┐                                                                    
//                                   val_5                                                                                                        val_1                                                                                                     val_9                                                                  
//            ┌────────────────────────┴────────────┬──────────────────────────────────┐                                     ┌──────────────────────┴────────────┬────────────────────────────────┐                                  ┌────────────────────────┴──────────────┬──────────────────────────────────┐                  
//          val_7                                 val_5                             val_10                                 val_3                               val_1                            val_6                             val_11                                   val_9                              val_2                
//    ┌───────┴────┬──────────┐             ┌───────┴────┬─────────┐          ┌────────┴─────┬──────────┐            ┌───────┴────┬─────────┐            ┌───────┴────┬─────────┐         ┌───────┴────┬─────────┐          ┌────────┴─────┬──────────┐             ┌────────┴────┬──────────┐          ┌───────┴────┬─────────┐   
//  val_8        val_7      val_10        val_6        val_5     val_8      val_11         val_10     val_5        val_4        val_3     val_6        val_2        val_1     val_4     val_7        val_6     val_1      val_12         val_11     val_2         val_10        val_9      val_12     val_3        val_2     val_9 

func TestRainTreeCompleteTwelveNodes(t *testing.T) {
    originatorNode := validatorId(1)
    var expectedCalls = TestNetworkSimulationConfig{
        originatorNode:  {1, 6},
        validatorId(2):  {3, 2},
        validatorId(3):  {2, 2},
        validatorId(4):  {2, 0},
        validatorId(5):  {2, 4},
        validatorId(6):  {3, 2},
        validatorId(7):  {2, 2},
        validatorId(8):  {2, 0},
        validatorId(9):  {2, 4},
        validatorId(10):  {3, 2},
        validatorId(11):  {2, 2},
        validatorId(12):  {2, 0},

    }
	testRainTreeCalls(t, originatorNode, expectedCalls)
}
```

## Required Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have tested my changes using the available tooling
- [x] I have updated the corresponding CHANGELOG

### If Applicable Checklist
- [ ] I have updated the corresponding README(s); local and/or global
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added, or updated, [mermaid.js](https://mermaid-js.github.io) diagrams in the corresponding README(s)
- [ ] I have added, or updated, documentation and [mermaid.js](https://mermaid-js.github.io) diagrams in `shared/docs/*` if I updated `shared/*`README(s)

### CODE REVIEW

**Comment by jeremybeal11** [comment]
I seem to have issues running the py sim from the instructions in the README file. 

After I run the command `rainTreeTestOutputFilename=/tmp/answer.go numRainTreeNodes=7 make p2p_test_generator` in the python folder.  The error I got was:
 make: *** No rule to make target p2p_test_generator'.  Stop.

When I ran the command outside of the python folder dir where the `Makefile` is located I got the following:
```
Traceback (most recent call last):
  File "python/test_generator.py", line 8, in <module>
    from simulator import Counters, print_results, simulate
  File "/.../rain-tree-sim/python/simulator.py", line 42, in <module>
    @dataclass
  File "/.../rain-tree-sim/python/simulator.py", line 45, in Counters
    nodes_reached: set[str]  # Nodes reached by current RainTree propagating
TypeError: 'type' object is not subscriptable
make: *** [p2p_test_generator] Error 1
```

**Comment by Olshansk** [comment]
@jeremybeal11 Did you run it off of main or the branch in this PR which hasn't been merged to main yet?

**Comment by jeremybeal11** [comment]
@Olshansk I ran it off of the `python_simulator` branch

**Comment by Olshansk** [comment]
> When I ran the command outside of the python folder dir where the Makefile is located I got the following:

Make commands ALWAYS need to be run in the same run in the same directory as where the `Makefile` exists https://superuser.com/questions/370575/how-to-run-make-file-from-any-directory

**Comment by Olshansk** [comment]
> TypeError: 'type' object is not subscriptable

Which version of python are you using? For me, it's

```
$ python3 --version
Python 3.10.8
````

Found this on StackOverflow potentially pointing to the fact that you might need python >= 3.9: https://stackoverflow.com/questions/26920955/typeerror-type-object-is-not-subscriptable-when-indexing-in-to-a-dictionary

**Comment by jeremybeal11** [comment]
> 

Yea, that's what I figured. Which is why I thought it was weird that I got the trace error. I checked my PY version, and it's 3.7, so I will update it now and try again.

**Comment by jeremybeal11** [comment]
> > TypeError: 'type' object is not subscriptable
> 
> Which version of python are you using? For me, it's
> 
> ```
> $ python3 --version
> Python 3.10.8
> ```
> 
> Found this on StackOverflow potentially pointing to the fact that you might need python >= 3.9: https://stackoverflow.com/questions/26920955/typeerror-type-object-is-not-subscriptable-when-indexing-in-to-a-dictionary

Got it, it was an issue with my Python version. Proceeding to run the rest of the sim.

**Comment by jeremybeal11** [comment]
@Olshansk, for clarity, 

In the PR, you said to run: `make test_p2p` command after I have copied the visual to `module_raintree_test.go` in the main V1 repo, but I'm getting:

```
make test_p2p
make: *** No rule to make target `test_p2p'.  Stop.
```
also in the demo you have a different command: 
`go test -v -count=1 -v ./p2p/... -run TestRainTreeCompleteTwelveNodes`

Can you clarify which command  I should be running and where I should run it?

**Comment by Olshansk** [comment]
Does it work if you don't make any changes?

The target should be there: https://github.com/pokt-network/pocket/blob/main/Makefile#L316

Screen Shot 2022-10-28 at 10 17 47 AM

**Comment by jeremybeal11** [comment]
@Olshansk what GO version are you using? I was able to get past the previous issue but now I'm getting another issue:
```
make: *** [test_p2p] Error 1
...
go get github.com/pokt-network/pocket/shared/debug
go: github.com/pokt-network/pocket/shared/debug: no matching versions for query "upgrade"
```

Also, I will be updating the README of the PY simulator to reflect the steps w/  env requirements for future contributors/ learners as well.

**Comment by Olshansk** [comment]
> what GO version are you using? I was able to get past the previous issue but now I'm getting another issue:

Can you take a look here and lmk if it helps: https://github.com/pokt-network/pocket/blob/main/docs/development/README.md#install-dependencies

> Also, I will be updating the README of the PY simulator to reflect the steps w/ env requirements for future contributors/ learners as well.

Ty!

**Comment by jeremybeal11** [comment]
> go test -v -count=1 -v ./p2p/... -run TestRainTreeCompleteTwelveNodes

Yea that's what I was using and was hitting build errors. I ultimately just had to rebuild everything a few times in a new env and I was able to finally get it to work. 

I was able to run the `make test_p2p` and  `go test -v -count=1 -v ./p2p/... -run TestRainTreeCompleteTwelveNodes` successfully. 

Thanks @Olshansk !

**Comment by Olshansk** [comment]
> Also, I will be updating the README of the PY simulator to reflect the steps w/ env requirements for future contributors/ learners as well.

I'll merge this in and feel free to send a followup PR.

> Yea that's what I was using and was hitting build errors. I ultimately just had to rebuild everything a few times in a new env and I was able to finally get it to work.

If you have repro steps, please improve!

**Comment by jeremybeal11** [comment]
@Olshansk mind if we get this PR merged so I can update the README?

**Review by andrewnguyen22 — APPROVED** [review]

**Comment by andrewnguyen22** [comment]
@jeremybeal11 sorry was probably blocking this - if you want - you can PR into this branch and then change it to main once it's merged so we can checkout your contributions without blocking

**Comment by Olshansk** [comment]
@jeremybeal11 Done! Also, when you have questions, please do organize & post them online. We can go over them synchronously in a call if need be.

Would be great for a community call in the future as well.

**Pull request merged**
